"""add field_data table

Hand-written rather than autogenerated: `flask db migrate` compares the model
metadata against a database built by `create-db`, which yields a large spurious
diff (it proposed dropping and recreating 37 unrelated tables and dropping a
runtime-created dynamic field column). Only the field_data table is created here.

Revision ID: a1c4e77b2d19
Revises: f0a3d6c1e8b2
Create Date: 2026-07-26

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a1c4e77b2d19"
down_revision = "f0a3d6c1e8b2"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "field_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_of_site", sa.String(), nullable=False),
        sa.Column("mission_date", sa.DateTime(), nullable=True),
        sa.Column("collected_data_by", sa.String(), nullable=True),
        sa.Column("data_types", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("type_of_site", sa.String(), nullable=True),
        sa.Column("no_of_site", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("total_photos", sa.Integer(), nullable=True),
        sa.Column("total_videos", sa.Integer(), nullable=True),
        sa.Column("total_interviews", sa.Integer(), nullable=True),
        sa.Column("translation", sa.String(), nullable=True),
        sa.Column("drone_photos", sa.Integer(), nullable=True),
        sa.Column("drone_videos", sa.Integer(), nullable=True),
        sa.Column("data_size_for_site", sa.String(), nullable=True),
        sa.Column("total_size", sa.String(), nullable=True),
        sa.Column("data_storage_location", sa.String(), nullable=True),
        sa.Column("legal_analysis", sa.Text(), nullable=True),
        sa.Column("analysis_by", sa.String(), nullable=True),
        sa.Column("analysis_date", sa.DateTime(), nullable=True),
        sa.Column("shared_with", sa.String(), nullable=True),
        sa.Column("modified_last_by", sa.String(), nullable=True),
        sa.Column("modified_last_date", sa.DateTime(), nullable=True),
        sa.Column("excavated_status", sa.String(), nullable=True),
        # inherited from BaseMixin
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_field_data_name_of_site", "field_data", ["name_of_site"])
    op.create_index("ix_field_data_mission_date", "field_data", ["mission_date"])
    op.create_index("ix_field_data_type_of_site", "field_data", ["type_of_site"])
    op.create_index("ix_field_data_code", "field_data", ["code"])
    op.create_index("ix_field_data_excavated_status", "field_data", ["excavated_status"])


def downgrade():
    op.drop_index("ix_field_data_excavated_status", table_name="field_data")
    op.drop_index("ix_field_data_code", table_name="field_data")
    op.drop_index("ix_field_data_type_of_site", table_name="field_data")
    op.drop_index("ix_field_data_mission_date", table_name="field_data")
    op.drop_index("ix_field_data_name_of_site", table_name="field_data")
    op.drop_table("field_data")
